name: 4. Model Training

on:
  workflow_dispatch:
    inputs:
      training_level:
        description: 'Choose model training level: nlp or supervised'
        required: true
        default: 'nlp'
        type: choice
        options:
          - nlp
          - supervised
      nlp_techniques:
        description: 'Comma-separated list of NLP techniques to apply (e.g., tfidf,w2v,sentiment,ngrams,lda,length)'
        required: false
        default: 'None'
        type: string

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-west-2

      - name: Run model training with NLP techniques
        if: ${{ github.event.inputs.nlp_techniques != 'None' }}
        run: |
          python src/${{ github.event.inputs.training_level }}_training.py --techniques ${{ github.event.inputs.nlp_techniques }}

      - name: Run model training without NLP techniques
        if: ${{ github.event.inputs.nlp_techniques == 'None' }}
        run: |
          python src/${{ github.event.inputs.training_level }}_training.py
